1. Import the NUMPY package under the name np.



In [1]:
import numpy as np

2. Print the NUMPY version and the configuration.

In [2]:
print(np.version.version)

1.17.2


3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.random((2,3,5))

4. Print a.

In [4]:
print(a)

[[[0.99109212 0.16306455 0.14594676 0.03710005 0.87007128]
  [0.200333   0.43375796 0.61983939 0.04492597 0.0629702 ]
  [0.87843213 0.36643684 0.33514689 0.06621487 0.62798453]]

 [[0.78817822 0.32683418 0.29603982 0.43395613 0.56067885]
  [0.27845384 0.11146818 0.9344507  0.21278814 0.54583175]
  [0.13716925 0.99753991 0.80226219 0.02371301 0.49273111]]]


5. Create a 5x2x3 3-dimensional array with all values equaling 1.
Assign the array to variable "b"

In [5]:
b = np.ones((5,2,3))

6. Print b.

In [6]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


7. Do a and b have the same size? How do you prove that in Python code?

In [7]:
if a.size == b.size:
        print('a and b arrays have the same size')

a and b arrays have the same size


8. Are you able to add a and b? Why or why not?

In [8]:
try:
    c = a+b
    print(c)
except:
    print("It's not possible to add 2 different arrays with different dimensions")

It's not possible to add 2 different arrays with different dimensions


9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [9]:
c = b.transpose(1,2,0)
#d = np.array(a).reshape(2,3,5) > it's not the same
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [10]:
d = a + c
#Because they have the same dimension

11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [11]:
print (a)
print (d)

[[[0.99109212 0.16306455 0.14594676 0.03710005 0.87007128]
  [0.200333   0.43375796 0.61983939 0.04492597 0.0629702 ]
  [0.87843213 0.36643684 0.33514689 0.06621487 0.62798453]]

 [[0.78817822 0.32683418 0.29603982 0.43395613 0.56067885]
  [0.27845384 0.11146818 0.9344507  0.21278814 0.54583175]
  [0.13716925 0.99753991 0.80226219 0.02371301 0.49273111]]]
[[[1.99109212 1.16306455 1.14594676 1.03710005 1.87007128]
  [1.200333   1.43375796 1.61983939 1.04492597 1.0629702 ]
  [1.87843213 1.36643684 1.33514689 1.06621487 1.62798453]]

 [[1.78817822 1.32683418 1.29603982 1.43395613 1.56067885]
  [1.27845384 1.11146818 1.9344507  1.21278814 1.54583175]
  [1.13716925 1.99753991 1.80226219 1.02371301 1.49273111]]]


12. Multiply a and c. Assign the result to e.

In [12]:
e = a*c
if np.array_equal(e,a):
    print("e and a are equal")
else:
    print("e and a are NOT equal")
#in this operation evary element is multyplied for 1 

e and a are equal


14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [13]:
d_max = d.max()
print(d_max)
d_min = d.min()
print(d_min)
d_mean = d.mean()
print(d_mean)

1.9975399109651986
1.0237130080205692
1.4261803941292703


15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [14]:
f = np.empty([2,3,5])
print(f)

[[[1.99109212 1.16306455 1.14594676 1.03710005 1.87007128]
  [1.200333   1.43375796 1.61983939 1.04492597 1.0629702 ]
  [1.87843213 1.36643684 1.33514689 1.06621487 1.62798453]]

 [[1.78817822 1.32683418 1.29603982 1.43395613 1.56067885]
  [1.27845384 1.11146818 1.9344507  1.21278814 1.54583175]
  [1.13716925 1.99753991 1.80226219 1.02371301 1.49273111]]]


16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

In [25]:
#print(f.shape)
#print(d.shape)

#print(d_min)
#print(d_mean)
#print(d_max)

#print(d)
f_list=[]
for x in d:
    #print(x)
    for y in x:
        for z in y:
            #print ('-',z)
            if z>d_min and z<d_mean:
                f_list.append(25)
            elif z>d_mean and z<d_max:
                f_list.append(75)
            elif z==d_mean:
                f_list.append(50)
            elif z==d_min:
                f_list.append(0)
            elif z==d_max:
                f_list.append(100)
                
f = np.array(f_list).reshape(2,3,5)
#print(f)

""" Another option to solve it but I couldnt finish
print(f.shape)
print(d.shape)
for xf,xd in f,d:
    print(xf)
    print(xd)
    for yf,yd in xf,xd:
        for zf,zd in yf,yd:
            #print ('-',z)
            if zd>d_min and zd<d_mean:
                zf = 25
                if zd>d_mean and zd<d_max:
                    zf=75
                    if zd==d_mean:
                        zf=50
                        if zd==d_min:
                            zf=0
                            if zd==d_max:
                                zf=100
print(d)
"""

" Another option to solve it but I couldnt finish\nprint(f.shape)\nprint(d.shape)\nfor xf,xd in f,d:\n    print(xf)\n    print(xd)\n    for yf,yd in xf,xd:\n        for zf,zd in yf,yd:\n            #print ('-',z)\n            if zd>d_min and zd<d_mean:\n                zf = 25\n                if zd>d_mean and zd<d_max:\n                    zf=75\n                    if zd==d_mean:\n                        zf=50\n                        if zd==d_min:\n                            zf=0\n                            if zd==d_max:\n                                zf=100\nprint(d)\n"

17. Print d and f. Do you have your expected f?
For instance, if your d is:

array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],
       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

In [24]:
print("d array")
print(d)
print("f array")
print(f)
#I checket it in last exercise

d array
[[[1.99109212 1.16306455 1.14594676 1.03710005 1.87007128]
  [1.200333   1.43375796 1.61983939 1.04492597 1.0629702 ]
  [1.87843213 1.36643684 1.33514689 1.06621487 1.62798453]]

 [[1.78817822 1.32683418 1.29603982 1.43395613 1.56067885]
  [1.27845384 1.11146818 1.9344507  1.21278814 1.54583175]
  [1.13716925 1.99753991 1.80226219 1.02371301 1.49273111]]]
f array
[[[ 75  25  25  25  75]
  [ 25  75  75  25  25]
  [ 75  25  25  25  75]]

 [[ 75  25  25  75  75]
  [ 25  25  75  25  75]
  [ 25 100  75   0  75]]]


18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:

array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],
       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""